name: "CI/CD Pipeline"

on:
  push:
    branches: [ "main", "feature/*" ]
    tags:
      - v*
  pull_request:
    branches: [ "main" ]

env:
  project_name: learning-gtest

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      build-output-dir: ${{ steps.strings.outputs.build-output-dir }}
      version: ${{ steps.strings.outputs.version }}
    steps:
      - uses: lukka/get-cmake@latest

      - uses: actions/checkout@v4

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
          COMMIT_HASH=${{ github.sha }}
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION=latest
          VERSION="$VERSION+sha.${COMMIT_HASH:0:8}"
          echo VERSION=$VERSION
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake --preset=default
          -DCPACK_PACKAGE_VERSION="${{ steps.strings.outputs.version }}"

      - uses: actions/upload-artifact@v4
        with:
          name: configure-${{ steps.strings.outputs.version }}
          path: ${{ steps.strings.outputs.build-output-dir }}

  libraries:
    runs-on: ubuntu-latest
    needs: [ configure ]
    steps:
      - uses: lukka/get-cmake@latest

      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: configure-${{ needs.configure.outputs.version }}
          path: ${{ needs.configure.outputs.build-output-dir }}

      - name: Build
        run: |
          cmake --build --preset=default

      - uses: actions/upload-artifact@v4
        with:
          name: libraries-${{ needs.configure.outputs.version }}
          path: ${{ needs.configure.outputs.build-output-dir }}

  tests:
    runs-on: ubuntu-latest
    needs: [ configure, libraries ]
    steps:
      - uses: lukka/get-cmake@latest

      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: libraries-${{ needs.configure.outputs.version }}
          path: ${{ needs.configure.outputs.build-output-dir }}

      - name: Test
        run: |
          ctest --extra-verbose --preset=default

      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-results
          path: "${{ needs.configure.outputs.build-output-dir }}/**/reports/junit-*.xml"

  package:
    runs-on: ubuntu-latest
    needs: [ configure, libraries ]

    steps:
      - uses: lukka/get-cmake@latest

      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: libraries-${{ needs.configure.outputs.version }}
          path: ${{ needs.configure.outputs.build-output-dir }}

      - name: Package
        run: |
          cpack --preset=default
          tar --list --file ${{ needs.configure.outputs.build-output-dir }}/${{env.project_name}}-*.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: package-${{ needs.configure.outputs.version }}
          path: ${{ needs.configure.outputs.build-output-dir }}/${{env.project_name}}-*

  release:
    runs-on: ubuntu-latest
    needs: [ configure, package, tests ]
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: package-${{ needs.configure.outputs.version }}
          path: ${{ needs.configure.outputs.build-output-dir }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ needs.configure.outputs.build-output-dir }}/${{env.project_name}}-*
